### ISSUE TITLE
Problems with loading user lists

### ISSUE THREAD

**Issue by xihels** [zhuyaliang/user-admin#11]
Loading the user list is an async call. 
Calling act_user_manager_list_users directly after act_user_manager_get_default may be wrong

This patch fix this problem
[fix-usrlist-is-empty.patch.gz](https://github.com/zhuyaliang/user-admin/files/2799862/fix-usrlist-is-empty.patch.gz)

**Comment by zhuyaliang** [comment]
@xihels 
Thank you very much for your suggestion. I overlooked this problem. I checked your patch. I don't think it's the best solution. After discussing with @yetist , It is considered that it is more reasonable to use the _"is-load"_ signal processing provided by _accountsservice_.
Thank you for your test.
