### ISSUE TITLE
Global test feedback

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#14]
First of all, I want to thank you for the great work. :+1: 
Here is my feedback, I hope it will help you making this app ever better !

1) The very first time I launched the application There was an error message to get the user language and indeed the language field in the GUI was blank (actually the language is always blank when I create a new user with adduer).

2) Whenever something is changed, the authentication window pops up. It would be more convenient imho to let the user set anything he wants and prompts for authentication when the user clicks on an "Apply" or "Save" button. Or better there should be an "Unlock" button in the title bar to make it consistent with what you have done for the groups.

3) The language list is way too long and unfortunately pressing a key doesn't jump to the languages starting with the letter corresponding to the key pressed (ie: F should jump to the first language starting with a F).
Or alternatively it would be great to only display the main languages and have a sub-menu with all the variants (i.e: English -> English (Canada), ..., English (Hong Kong), ..., English (Zimbabwe))

4) The login is not displayed (just the name). It would be nice to display it somewhere

5) When the group window is resized (height), it [adds empty space below the "Close" button](https://i.imgur.com/DthOr0M.png) instead of expanding the group list (in the switch tab) although there is a scrollbar.

**Comment by zhuyaliang** [comment]
Thank you very much for your suggestion. I will revise it. I'll let you know when everything is read

**Comment by zhuyaliang** [comment]
@kyrios123 I have made some improvements in the light of your suggestions.
However, I did not understand this recommendation.
> 4\. The login is not displayed (just the name). It would be nice to display it somewhere

My understanding is to display the user name and real name of the user as well.

**Comment by kyrios123** [comment]
For the point 4 what I mean is that the **user name** is displayed but not the **login**. It would be nice to show them both.

In the example my user name is **Pierre-Yves** while my login is **py**. A lambda user will not care but a more advanced user will probably like to see the login as well since it's what he uses to login on the console, do a ssh connection, etc...
Also it is technically possible to have multiple users (with different logins) that have the same user name. [Here is an illustration](https://i.imgur.com/axxZ7sK.png) of this special case. It's hard to know which "Pierre-Yves" is py and which Piere-Yves is toto.

PS: The username is editable (which is fine), but there is no save/apply button and the authentication window doesn't pops up when it's changed so I can't (for example) change one of the Pierre-Yves into something else.

**Comment by zhuyaliang** [comment]
@kyrios123 Your suggestion is very good.I overlooked the problem of two users having the same username,I've fixed this problem and you can test it.

**Comment by kyrios123** [comment]
@zhuyaliang that's awesome ! All the points I raised have been addressed :)

If you don't mind I have a few more remarks following the tests I made today

1. The user name is still editable, but there is no way (I found) to save it

2. On the window to select a picture, there is no close/cancel button (it can be close by clicking on the main "Mate User Manage" window but it's not obvious to guess it.

3. I don't speak English fluently but I don't think "User Manage" and "Groups Manage" sound good (also singular form is used for user while plural is used for groups). Wouldn't it be better to use one ot these
- Mate User Manage**r** and **Mate** Group Manage**r** 
- Mate Manage User**s** and  **Mate** Manage Groups

4. It would be nice to have the possibility to click on "Setting Groups" without having to unlock the user (to check to which groups a user belongs to for example)

5. When you unlock the users, then click on "Setting Groups", the "Groups Manage" is still locked and a 2nd unlock is required.  If both could be locked/unlocked together it would be user friendlier (if not too complex to implement)

6. The password field and the user name field are not greyed out (disabled) when the user is locked

7. On the "Create Group" tab, the fields are not greyed out (disabled) when the groups are locked

**Comment by zhuyaliang** [comment]
@kyrios123 
 Hello, thank you for your test feedback.
1. After changing the name, the Enter key saves the modification,I will add the text tip.
2. I think the window that chooses pictures will be more beautiful with no title bar，Clicking on the main window closes the window, and I'll add a text tip.
3. I'm sorry. My English is not very good, but I will ask others for advice.Consult native speakers of English
4. > It would be nice to have the possibility to click on "Setting Groups" without having to unlock the user (to check to which groups a user belongs to for example)

   This is a good idea.
5. If I adopt Article 4,So group management needs a separate unlock button
6. Users have the right to modify their names, so there is no need to disable the current login user's ability to modify their names.Disabling password modification is a good suggestion.
7. create user group, I disabled the confirmation button, so it is impossible to create a group successfully without unlocking it.

**Comment by zhuyaliang** [comment]
@kyrios123 I've made a new change. You can test the effect.

**Comment by kyrios123** [comment]
@zhuyaliang 
FYI - I just updated MATE from 1.21.x to 1.22.0

1. Now I can't create a new user anymore, [the application "disappear"](https://i.imgur.com/ckF12Xy.gif) when I click on the create button.

2. Wasn't the language selection list improved, it looks like the older version. It's really not easy to use and if you scroll up when it's open [you can navigate into blank items](https://i.imgur.com/VZYeS4F.gif)

3. When you set the password for a new user (Label should be "Set the password now"), there is immediately an error message that appears even before you can get a chance to type anything and [the message causes the window to become wider](https://i.imgur.com/KpfSJWT.gif) which is weird.
Also shouldn't it be _8 characters_ instead of _8 bits_ in the message ?

4. The image set isn't integrated into MATE. You can see it in the "[About me](https://i.imgur.com/zXGq8eQ.png)" application and on the [lock screen](https://i.imgur.com/lVZ1Y5q.png) as well

**Comment by zhuyaliang** [comment]
@kyrios123 
>Now I can't create a new user anymore, the application "disappear" when I click on the create button.

I did not reproduce this phenomenon.After updating mate to 1.22, I can create users normally.Is there any error message after the window exits? For example, Segmentation fault，If you don't choose a language, will you still have this problem if you use the default language directly?

**Comment by kyrios123** [comment]
@zhuyaliang Here is what I found in the journal logs
```
mars 10 12:23:14 mate122 mate-user-admin[988]: Could not get current seat: Aucune donnée disponible
mars 10 12:23:24 mate122 polkitd[611]: Operator of unix-session:c1 successfully authenticated as unix-user:py to gain TEMPORARY authorization for action org.mate.user.admin.admi>
mars 10 12:23:38 mate122 mate-user-admin[988]: mate_get_language_from_locale: assertion '*locale != '\0'' failed
mars 10 12:23:38 mate122 accounts-daemon[599]: request by system-bus-name::1.63 [mate-user-admin pid:988 uid:1000]: create user 'UserTwo'
mars 10 12:23:38 mate122 accounts-daemon[599]: useradd: invalid user name 'UserTwo'
mars 10 12:23:38 mate122 mate-user-admin[988]: [165B blob data]
mars 10 12:23:38 mate122 kernel: traps: mate-user-admin[988] trap int3 ip:7f63e34d7465 sp:7fff0f2a9ca0 error:0 in libglib-2.0.so.0.5600.3[7f63e349f000+7c000]
mars 10 12:23:38 mate122 audit[988]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj==unconfined pid=988 comm="mate-user-admin" exe="/usr/bin/mate-user-admin" s>
```
I can however create the user (same name) from the terminal. See [here](https://i.imgur.com/0C1LpOm.png)

**Comment by zhuyaliang** [comment]
@kyrios123 I found the cause of the problem，The useradd command cannot create a user name (home directory) containing uppercase letters。
for example：
> useradd -c “user2" UserTwo

So when you create a new user, you need to change the location of two names.
![2019-03-11 02-05-39屏幕截图](https://user-images.githubusercontent.com/36913152/54096097-58ecda80-43e5-11e9-9d96-428da9597e70.png)
I'll add an error message.

**Comment by kyrios123** [comment]
I think I'm lost... `useradd -c "UserTwo" user2` worked fine for me from a terminal.
And the man page says any string, so I am pretty sure it could even contain while spaces and punctuation.
>       -c, --comment COMMENT
>           Any text string. It is generally a short description of the login,
>           and is currently used as the field for the user's full name.

It shouldn't use the comment field (username) to create the home directory but the login !?

In my [previous example](https://i.imgur.com/0C1LpOm.png), **user2** is the login and is also used to create the home directrory. **UserTwo** is the user name (which actually is a comment field according to the man page of useradd).

Does this make sense or did I miss something ?

**Comment by zhuyaliang** [comment]
@kyrios123 
You can try ```useradd-m USER```
> useradd -c "UserTwo" user2

*UserTwo* is a login name that can contain any string,But not the name of the home directory.
*user2* is the name of the user and also the name of the home directory. It should not contain uppercase letters.
Your previous wrong operation is equivalent to executing the 
>useradd -c  "user2"  UserTwo 

command
That is, the home directory cannot contain capital letters.

**Comment by kyrios123** [comment]
Actually I think the confusion is we use different vocabulary I guess
![image](https://user-images.githubusercontent.com/7815316/54224584-1bc63c80-44fa-11e9-879b-bee5681f44f6.png)

What you call user name is what I call login and vice-versa.
For me user2 is the login (this is what I type to identify at console prompt) and user name is UserTwo.

In the man pages it's also called login
>NAME
>       useradd - create a new user or update default new user information
>
>SYNOPSIS
>       useradd [options] LOGIN

**Comment by zhuyaliang** [comment]
@kyrios123 
I see what you mean. This is the question of the *useradd command. I'll ask them this question. How do you feel?

**Comment by JoshStrobl** [comment]
Instead of "Login Name", what about having it similar to GNOME Control Center's "Full Name" so it's clearer that we're referencing the user's name? Furthermore, "User Name" should be "Username".
