### ISSUE TITLE
user picture

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#19]
When a user changes his picture via the "About me" application, it's saved in `~/.face` this picture is then used in different places like on the lock screen for example.

When I change the picture from "MATE User Manager", it is saved somewhere else `~/.face` is unchanged and this updated picture is visible only in "MATE User Manager" and nowhere else !?

**Comment by zhuyaliang** [comment]
This is because we use different interfaces. I use the interface provided by account service to manage users. In the near future, I will make a request to mate-desktop to use the account service API (lock screen).
