### ISSUE TITLE
Change user language does not work

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#20]
I changed my user language then I did log off and log in again, but it didn't make any difference, everything is still in English.

According to what I found on [ArchLinux wiki](
https://wiki.archlinux.org/index.php/locale#Overriding_system_locale_per_user_session),  there should be a ` ~/.config/locale.conf` file but I can't find it.

1.  Edit a user, change the language (let's say french), apply the change.
2.  Log off and log in with the user that was just edited, the session language **is not** in french
3.  Check if ` ~/.config/locale.conf` exists -> no
4.  Check the language of the user in user-admin -> It's set to french.

**Comment by zhuyaliang** [comment]
I'm sorry to have taken so long to reply to you. I've fixed the problem that language switching doesn't work.
