### ISSUE TITLE
unlock/lock icons are inverted.

### ISSUE THREAD

**Issue by Thyname** [zhuyaliang/user-admin#24]
The lock/unlock icons should show the current state. So in the 'unlock' button the icon must be the locked padlock (to show that it is currently locked) and then when unlocked, the 'lock' button should display the unlocked padlock.

**Comment by zhuyaliang** [comment]
[gtk_lock_button_new](https://developer.gnome.org/gtk3/stable/GtkLockButton.html#GtkLockButton.description)。

**Comment by Thyname** [comment]
Ah, ok. It felt strange for me as it's the other way in Seahorse, where the icon is used to show if a keyring is locked or unlocked.
