### ISSUE TITLE
Make desktop file 'desktop agnostic'.

### ISSUE THREAD

**Issue by Thyname** [zhuyaliang/user-admin#25]
mate-user-desktop can work fine for other DEs like Xfce and LXDE, so mate-user-admin.desktop can be more neutral. For example:

- Change name to 'User Manager'.
- Add XFCE and LXDE to OnlyShowIn key.

Below is a sample, with corrected Comment key (and with added pt_BR entries):

[Desktop Entry]
Name=User Manager
Name[pt_BR]=Gestor de Usuários
Name[ca]=Gestor d'usuaris
Name[zh_CN]=用户管理
Comment=Manage user accounts
Comment[pt_BR]=Gerenciar contas de usuários
Comment[ca]=Gestioneu els usuaris
Comment[zh_CN]=管理用户权限、语言、密码、登录名称、头像。
Categories=GTK;Settings;System;Utility;
Keywords=Configuration;Utility;
OnlyShowIn=MATE;XFCE;LXDE;
Exec=mate-user-admin
Icon=system-users
Terminal=false
Type=Application
X-Desktop-File-Install-Version=0.23

- Note: icon name here is changed, I'll open another issue for this suggestion.

**Comment by Thyname** [comment]
At the moment I don't have a standalone window manager installed (like icewm, openbox etc.), only Xfce, but I'm thinking that maybe if OnlyShowIn is used the app could not appear in their menus. If this is the case, then it would be better to simply use NotShowIn instead, for DEs that already have user manager apps.
So if we suppose that Gnome and KDE would be the ones excluded, the desktop file wouldn't need the OnlyShowIn key and would then have:

NotShowIn=GNOME;KDE;

**Comment by zhuyaliang** [comment]
I currently use ```mate desktop``` environment, ```mate-user-admin``` works well under mate, so ```OnlyShowIn = MATE```.I'm not sure ```mate-user-admin``` works well in other desktop environments.

**Comment by Thyname** [comment]
Ok. I'm on Xfce and basic things that don't depend on the DE like adding/removing the user, managing groups and login time work fine (didn't test changing account type).
Automatic login, I don't know. Does it depend on a specific display manager?

One thing that didn't work was that I created a new user and set to ask for password next time. Then lightdm asked to create the password at login ("administrator enforced to change the password" or something like that) but it didn't work as the dialog would just pop-up again and again.

So if it depends on something that's specific to MATE (like the DM), then sure, it should have this restriction.
