### ISSUE TITLE
Window title (and other little things).

### ISSUE THREAD

**Issue by Thyname** [zhuyaliang/user-admin#26]
Window title is currently 'Mate User Manage'. I think it's missing an 'r', like 'MATE User Manager', although it could also be just 'User Manager'.

I think also that it should use the 'system-users' icon - which is present in maybe all icon themes and so follows the look chosen for the desktop - both for the application icon and the desktop file.

**Comment by zhuyaliang** [comment]
> Window title is currently 'Mate User Manage'. I think it's missing an 'r', like 'MATE User Manager', although it could also be just 'User Manager'.

I'll fix this grammatical problem.
Using custom icons is more beautiful and can be distinguished from other applications using ```system-users``` icon

**Comment by zhuyaliang** [comment]
@Thyname 
This problem has been fixed.
