### ISSUE TITLE
Double authentication prompt for adding a new user

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#27]
1. Launch mate-user-admin
2. Click on the Unlock button -> **Authentication prompt**
3. Type the password
4. Click on Add user 
5. Fill in the form (login, user name, ...)
6.  Click on confirm -> **Authentication prompt** -> NOT OK

This 2nd authentication prompt is not necessary since user was already asked for admin password to unlock the application in point 2 -> 3.
Also this is inconstant with the Remove user functionality:

1. Launch mate-user-admin
2. Click on the Unlock button -> **Authentication prompt**
3. Type the password
4. Select a user
5. Click on Remove user 
6. Click yes on the confirmation message -> **Not asked a 2nd time for authentication** -> OK

**Comment by zhuyaliang** [comment]
Adding a new user actually does two things
1 Create Users
2 Group Management for New Users
So you need to authenticate twice.
To delete a user, you only need to delete the user，No without group management, so you only need to authenticate once.
When you need to use the group management function, even if you have user authentication on the main page, you need to re-authenticate when you enter the group management page.
Two validations correspond to two ```DBus``` services
User management uses ```accountsservice```
Group management using ```group-service```
So you need to authenticate twice.

**Comment by JoshStrobl** [comment]
Hey @zhuyaliang, thank you for your continued work on user-admin and quick responses to @kyrios123, it really is appreciated.

I understand that it is a separate dbus interface and has a separate polkit policy. For GNOME Control Center, they use the PolicyKit's annotate key to effective indicate that the user is also authorized for any action listed in the annotation. Per the [PolicyKit documentation](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html):

> The org.freedesktop.policykit.imply annotation (its value is a string containing a space separated list of action identifiers) can be used to define meta actions. The way it works is that if a subject is authorized for an action with this annotation, then it is also authorized for any action specified by the annotation. A typical use of this annotation is when defining an UI shell with a single lock button that should unlock multiple actions from distinct mechanisms. 

GNOME Control Center leverages this by having the individual authentication with their [user-accounts](https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/panels/user-accounts/org.gnome.controlcenter.user-accounts.policy.in#L18) policy, which has an annotation key for multiple other interfaces, see below:

```
<annotate key="org.freedesktop.policykit.imply">org.freedesktop.accounts.user-administration org.freedesktop.realmd.configure-realm org.freedesktop.realmd.login-policy</annotate>
```

Would it be a viable solution to leverage this in group-service's policy, except including accountservice in the imply, and effectively authenticating the user against group-service **first**, thus negating the secondary prompt for adding the user (via account service)?

**Comment by zhuyaliang** [comment]
@JoshStrobl 
That's a good idea.
```<annotate key="org.freedesktop.policykit.imply">org.freedesktop.accounts.user-administration  org.group.admin.group-administration org.group.admin.change-own-user-data org.freedesktop.realmd.configure-realm org.freedesktop.realmd.login-policy org.freedesktop.accounts.change-own-password</annotate>```
In this way, all authentication can be included.Thank you for reminding me

**Comment by zhuyaliang** [comment]
@kyrios123 Can I close this issue？

**Comment by kyrios123** [comment]
Sure, thanks!
