### ISSUE TITLE
Polkit authentication window is not translated

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#36]
Polkit window is in english while user-admin is in french

![image](https://user-images.githubusercontent.com/7815316/66676528-010e9e80-ec68-11e9-9ee6-5050ec8f65c1.png)

**Comment by zhuyaliang** [comment]
@kyrios123  The reason for this problem is that the ```org.group.admin.policy``` content in ```group-service``` is not translated.Later, I will add ```group-service``` to ```transifex```
