### ISSUE TITLE
Segfault because I couldn't get the permission

### ISSUE THREAD

**Issue by rbuj** [zhuyaliang/user-admin#39]
https://github.com/zhuyaliang/user-admin/blob/54778185f1d3a713cef34cfae021fe8a56b66139/src/main.c#L117

![Screenshot at 2020-02-02 16-59-45](https://user-images.githubusercontent.com/10171411/73611083-94385f00-45de-11ea-925b-6bc223fc5878.png)

```shell
$ pkg-config --modversion polkit-gobject-1 gtk+-3.0
0.116
3.24.11
```

**Comment by rbuj** [comment]
It was SELinux :D

**Comment by zhuyaliang** [comment]
@rbuj Thank you for your modification. I'm sorry that I didn't reply to you in time due to the Spring Festival and the epidemic。Do you solve the problem？

**Comment by rbuj** [comment]
I remember that it worked on Fedora 30, so I took a look at the log on Fedora Rawhide, and it was a SELinux issue. I temporarily disabled it and then your app also worked without any issues.
