### ISSUE TITLE
PID file is not deleted when leaving the application

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#41]
Steps to reproduce
1- Launch the application
2- Exit the application
3- The file `/tmp/mate-user-admin.pid` still exists

Why is this a problem?
Because  is you "swtich user", the other user won't be able to use the application as the PID file exists already and will be owned by another user.

**Comment by zhuyaliang** [comment]
@kyrios123 
Try the latest submission. This PID file will be deleted every time you exit the program

**Comment by zhuyaliang** [comment]
Can I close this issues

**Comment by kyrios123** [comment]
Sure, @zhuyaliang 
Thanks !
