### ISSUE TITLE
Dark themes, some fonts color should become white instead of black

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#45]
When using dark themes, some fonts should be white instead of black (i.e. the users that are not selected in the left area of the main screen)

![image](https://user-images.githubusercontent.com/7815316/128089491-1bba374b-3c1a-4b85-90c9-13779eabdff6.png)

**Comment by zhuyaliang** [comment]
Sorry, there is something wrong with my PC, so I replied so late. The latest submission fixed this problem

**Comment by kyrios123** [comment]
Closed by fe00805194e9bd7649c98ba4b02aa7c3deb23785
