### ISSUE TITLE
user-admin does not install 

### ISSUE THREAD

**Issue by Heus-Sueh** [zhuyaliang/user-admin#46]
![Screenshot_2022-02-06_19-31-50](https://user-images.githubusercontent.com/98482469/152704492-30da584a-d31e-492a-9492-a3f6f0f2ab1f.png)

../data/meson.build:30:5: ERROR: Function does not take positional arguments.

A full log can be found at /home/matheus/.cache/paru/clone/group-service/src/group-service-1.3.0/builddir/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'group-service-1.3.0-1': 
==> Making package: user-admin 1.6.0-1 (dom 06 fev 2022 19:31:26)
==> Retrieving sources...
  -> Found 1.6.0.tar.gz
==> Validating source files with sha256sums...
    1.6.0.tar.gz ... Passed
-==> Making package: user-admin 1.6.0-1 (dom 06 fev 2022 19:31:27)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> group-service
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
error: failed to build 'user-admin-1.6.0-1': 
error: packages failed to build: group-service-1.3.0-1  user-admin-1.6.0-1

**Comment by zhuyaliang** [comment]
@Heus-Sueh Lack of dependency [group-service](https://github.com/zhuyaliang/group-service)

**Comment by Heus-Sueh** [comment]
compile group-service is not working, I do not know why 

![image](https://user-images.githubusercontent.com/98482469/153448521-6c603344-77a4-4342-b869-30ebb1604a82.png)

[meson-log.txt](https://github.com/zhuyaliang/user-admin/files/8042490/meson-log.txt)

**Comment by zhuyaliang** [comment]
@Heus-Sueh Thank you for your issues。
[meson-issues](https://github.com/mesonbuild/meson/issues/9441)
I will fix this problem as soon as possible

**Comment by Heus-Sueh** [comment]
thanks man

**Comment by zhuyaliang** [comment]
The problem was fixed 
[group-service](https://github.com/zhuyaliang/group-service/commit/951041f6dd13f95259e0399dfbf14568a39844fd)
[user-admin](https://github.com/zhuyaliang/user-admin/commit/1cc46ba1abcf1e6a65a427cd8cd06fea83e81c9d)
