### ISSUE TITLE
mate-user-admin package for Debian and Ubuntu is needed

### ISSUE THREAD

**Issue by N0rbert** [zhuyaliang/user-admin#49]
Thank you for this great application.

At present time it compiles normally on latest Ubuntu MATE 22.04 LTS by using below commands:

```
sudo apt-get install meson cmake pkg-config libgtk-3-dev libpwquality-dev libaccountsservice-dev libmate-desktop-dev git

cd ~/Downloads
git clone https://github.com/zhuyaliang/group-service
cd group-service/
meson build -Dprefix=/usr #meson build -Dprefix=/usr/local
ninja -C build
sudo ninja -C build install

cd ~/Downloads
git clone https://github.com/zhuyaliang/user-admin
cd user-admin/
meson build -Dprefix=/usr #meson build -Dprefix=/usr/local
ninja -C build
sudo ninja -C build install
```

It runs but does not have an icon in MATE Control Center, see 

![mate-user-admin@jammy](https://user-images.githubusercontent.com/309456/168030090-eba5086b-7458-457e-b1ec-5d490aca5ad2.png)

But it would be better if someone create special *debian* folder with all necessary files to ease package creation for Debian and Ubuntu. Thus two deb-packages (along with https://github.com/zhuyaliang/group-service/issues/4) will exist and users will be happy to use your tool.

**Comment by zhuyaliang** [comment]
Try running ```gtk-update-icon-cache /usr/share/icons/hicolor/``` to update the icon cache for the current theme
You can set up new avatars for users,The default avatar of all new users is this __empty avatar__
The package of ```deb``` may need the support of people in ```Debian and Ubuntu``` community. I very much hope that these two projects(**group-service and user-admin**) can appear in the repos of ```Debian and Ubuntu```.
Thank you very much for your advice

**Comment by zhuyaliang** [comment]
@N0rbert Try [8429e19f](https://github.com/zhuyaliang/user-admin/commit/8429e19f5b2e2af34d510771b4e943a55bf05a3c)

**Comment by N0rbert** [comment]
Thanks, now icons are in place.

I found other issue - when installed into `/usr/local` I do not see *Unlock* button. 
For which repository (group-service or user-admin) I should file this issue?

**Comment by zhuyaliang** [comment]
Let's continue to discuss and solve the problem here。
Here's the problem
```
polkit_permission_new_sync (USER_ADMIN_PERMISSION, NULL, NULL, &error);
```
```
A mechanism need to declare a set of actions in order to use polkit. Actions correspond to operations that clients can request the mechanism to carry out and are defined in XML files that the mechanism installs into: /usr/share/polkit-1/actions directory.
```
Will ```org.mate.user.admin.policy``` installing to ```/usr/local/``` will result in  ```policykit_permission_new_sync``` call failed

**Comment by N0rbert** [comment]
Thanks, I understood.
