### ISSUE TITLE
mate-user-admin Switch Bug

### ISSUE THREAD

**Issue by Khayasen** [zhuyaliang/user-admin#56]
**Expected behaviour**
The automatic logon appears like a normal switch

**Actual behaviour**
The switch looks stretched and enlarged

**Steps to reproduce the behaviour**
run mate-user-admin

**MATE general version**
Mate 1.26.0

**Package version**
Can't find the way to find it.

**Linux Distribution**
Ubuntu Mate (Kinetic Kudu) 22.10

![Screenshot at 2022-11-11 12-39-40](https://user-images.githubusercontent.com/103806906/201320677-28996188-3360-40ec-bab1-408a29f327d4.png)

**Comment by zhuyaliang** [comment]
[patch.tar.gz](https://github.com/zhuyaliang/user-admin/files/10112876/patch.tar.gz)
Can you help me test whether this patch can fix this problem

**Comment by rcusnir** [comment]
There is a crash report created on similar issue oin Fedora bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2222441

The error is caused by crash of accounts service daemon

**Comment by raveit65** [comment]
@rcusnir Can you please test this scratch build for f38 with mentioned patch above?
https://koji.fedoraproject.org/koji/taskinfo?taskID=103282947
Ignore i686 build error because of missing build dependency for this arch.

**Comment by zhuyaliang** [comment]
@rcusnir Should open a new issues

**Comment by rcusnir** [comment]
> @rcusnir Should open a new issues

New issue: https://github.com/zhuyaliang/user-admin/issues/59
