### ISSUE TITLE
 Default language problem

### ISSUE THREAD

**Issue by annasmithforos** [zhuyaliang/user-admin#58]
Hello. I've done a fresh install of the latest version of Mate, Version 22.10 (Kinetic Kudu) 64-bit. The default language is Spanish, and as a secondary I have added Catalan. My problem is that the user administration program has remained in Catalan and I am not able to change it. From preferences, personal, language support, I haven't been able to make it change, not even after uninstalling Catalan... It's not something really problematic, I'm bilingual, but it annoys me when something doesn't quite work. Clarify that it is the only program that has been "stuck" in Catalan. The rest is in Spanish. 
![Captura de pantalla -2023-03-09 19-26-38](https://user-images.githubusercontent.com/127437263/224120759-190514a2-166a-4e0f-b0e6-b4b72771f270.png)
Greetings.

**Comment by zhuyaliang** [comment]
@annasmithforos Click the ```unlock``` button to enter the password and open the language dialog box to select the language you need.It will take effect after reboot

**Comment by annasmithforos** [comment]
Thanks, but I don't see any button to change the language of the program. Could it be that I don't have it installed correctly? I don't know if it's safe to uninstall and reinstall it... I've looked in Synaptic and haven't found anything missing (that I can see...).
Greetings.
![Captura de pantalla -2023-03-10 12-34-06](https://user-images.githubusercontent.com/127437263/224306543-ca626442-4b79-4539-879c-3a3e23b9576a.png)

**Comment by zhuyaliang** [comment]
Run ```locale``` to view the current system language

**Comment by annasmithforos** [comment]
I have uninstalled Catalan, default English and returned to Spanish. It has remained in English (only this program, the rest it changes). I insist that it is a minor problem, it just bothers me that it does not work correctly.
Thanks for your interest.
LANG=es_ES.UTF-8
LANGUAGE=es_ES:en
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC=es_ES.UTF-8
LC_TIME=es_ES.UTF-8
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=
![Captura de pantalla -2023-03-13 13-07-04](https://user-images.githubusercontent.com/127437263/224698264-05a832b8-aec6-4129-9c0d-68278b828439.png)

**Comment by zhuyaliang** [comment]
Try to open ```mate-user-admin``` in the command line

**Comment by annasmithforos** [comment]
The result is the same. Anyway, I think it's best to leave it as it is.
Greetings.
![Captura de pantalla -2023-03-14 13-09-50](https://user-images.githubusercontent.com/127437263/224997374-9de6c3f0-a70a-42d5-a2c4-dc0b45aaaa0c.png)

**Comment by zhuyaliang** [comment]
Can you try to recompile the installation
```
meson build -Dprefix=/usr
ninja -C build
sudo ninja -C build install
```

**Comment by annasmithforos** [comment]
I'm sorry. I don't know how to use it.
***@***.***:~$ meson build -Dprefix=/usr

ERROR: Neither directory contains a build file meson.build.
***@***.***:~$

**Comment by zhuyaliang** [comment]
@annasmithforos We should do these operations after downloading the source code
```
git clone https://github.com/zhuyaliang/user-admin
cd user-admin
meson build -Dprefix=/usr
ninja -C build
sudo ninja -C build install
```

**Comment by annasmithforos** [comment]
Thanks!
Well, step by step but slowly...
The Meson build system
Version: 0.63.2
Source dir: /home/maria/Descargas/user-admin-master
Build dir: /home/maria/Descargas/user-admin-master/build
Build type: native build
Project name: mate-user-admin
Project version: 1.7.0
C compiler for the host machine: cc (gcc 12.2.0 "cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fstack-protector-strong: YES 
Compiler for C supports arguments -g: YES 
meson.build:67: WARNING: Consider using the built-in debug option instead of using "-g".
Compiler for C supports arguments -Waggregate-return: YES 
Compiler for C supports arguments -Warray-bounds: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wclobbered: YES 
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wextra: YES 
meson.build:67: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wformat-signedness: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Winline: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-strict-aliasing: YES 
Compiler for C supports arguments -Wno-suggest-attribute=format: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wpacked: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wreturn-type: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-aliasing: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wunused-but-set-variable: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
WARNING: -Wl,-z,relro looks like a linker argument, but has_argument and other similar methods only support checking compiler arguments. Using them to check linker arguments are never supported, and results are likely to be wrong regardless of the compiler you are using. has_link_argument or other similar method can be used instead.
Compiler for C supports arguments -Wl,-z,relro: YES 
WARNING: -Wl,-z,now looks like a linker argument, but has_argument and other similar methods only support checking compiler arguments. Using them to check linker arguments are never supported, and results are likely to be wrong regardless of the compiler you are using. has_link_argument or other similar method can be used instead.
Compiler for C supports arguments -Wl,-z,now: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gtk+-3.0 found: YES 3.24.34
Run-time dependency pwquality found: YES 1.4.4
Run-time dependency accountsservice found: YES 22.08.8
Found CMake: /usr/bin/cmake (3.24.2)
Run-time dependency group-service found: NO (tried pkgconfig and cmake)

meson.build:94:0: ERROR: Dependency "group-service" not found, tried pkgconfig and cmake

A full log can be found at /home/maria/Descargas/user-admin-master/build/meson-logs/meson-log.txt


But...
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory

**Comment by zhuyaliang** [comment]
@annasmithforos Thank you for your cooperation. You need to resolve the dependency before compiling ```user-admin```
```
git clone https://github.com/zhuyaliang/group-service
cd group-service
meson build -Dprefix=/usr
ninja -C build
sudo ninja -C build install
```
After the ```group-service``` compilation and installation are successful, we continue to compile ```user-admin```

```
cd user-admin
meson build -Dprefix=/usr
ninja -C build
sudo ninja -C build install
```
Thank you for your support for ```user-admin```. I will do better

**Comment by annasmithforos** [comment]
> I will do better
Oh no, don't worry. The problem is surely me, I'm not too expert. Now I'm on a trip. I'll check it out on Monday when I come back.
Thanks for everything.

**Comment by annasmithforos** [comment]
Hello again. Now it has worked correctly. I have done it inside a folder in home. How can I make it on a site so that the Mate user admin program is reconfigured?
Thank you for your patience.

**Comment by zhuyaliang** [comment]
>How can I make it on a site so that the Mate user admin program is reconfigured?

Do you mean that after executing the command ```apt get install mate-user-admin```, ```mate-user-admin``` can be used normally?

**Comment by annasmithforos** [comment]
Yes, it rules. Thank you for your patient help.
Best regards.

**Comment by zhuyaliang** [comment]
This is the packaging method for ```Debian``` installation packages
https://github.com/zhuyaliang/user-admin#create-deb-package-on-ubuntu-mate-2204-lts

Using ```dpkg -L mate-user-admin```, you can view the file list of the installation package. I think the installation location of the translation file may be incorrect. If this is the case, you need to contact the ```Ubuntu``` developer. I believe they will fix it soon.

**Comment by annasmithforos** [comment]
Yes I think you are right. I will do so. Thanks again for everything.

**Comment by zhuyaliang** [comment]
@annasmithforos Whether the problem has been solved ？

**Comment by annasmithforos** [comment]
Yes, you can close issue. Thank you.
