### ISSUE TITLE
[Feature Request] Manage groups

### ISSUE THREAD

**Issue by kyrios123** [zhuyaliang/user-admin#8]
In the `gnome-system-tools` users-admin, there is a "manage groups" button which I haven't seen on the screenshots. I would be nice to have a similar feature.

![image](https://user-images.githubusercontent.com/7815316/50053437-5441be80-0135-11e9-8687-4e6e7ffb0469.png)

**Comment by zhuyaliang** [comment]
@kyrios123 I also have the same idea. The service of using Dbus to manage user groups has been completed. Now it is being tested. After passing the test, I will join the group management content. If you are interested, you can see: https://github.com/zhuyaliang/group-service，Thank you for your advic

**Comment by zhuyaliang** [comment]
@kyrios123 
I have added the group management function, you can test and make suggestions.

**Comment by kyrios123** [comment]
Thanks @zhuyaliang that's great.
Unfortunately I scratched my MATE 1.21 virtual machine a week ago... 
When I'll rebuild mate desktop, I'll let you know.  On your side, please let me know when the application is mature enough for working on the translations.

**Comment by kyrios123** [comment]
@zhuyaliang I guess this one can be closed now :)
